import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 50,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  headerTitle: {
    flex: 1,
    marginHorizontal: 10,
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  tabContainer: {
    flex: 1,
  },
  tabBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#FF7029",
  },
  tabButton: {
    paddingVertical: 12,
  },
  tabText: {
    fontSize: 16,
    color: "#FFF",
  },
  activeTabText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFF",
    borderBottomWidth: 2,
    borderBottomColor: "#FFF",
  },
  infoTitle: {
    flex: 1,
    marginHorizontal: 10,
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  scrollViewStyle: {
    maxHeight: 200,
    overflow: "scroll",
  },
  infoText: {
    fontSize: 16,
    color: "#fff",
    marginTop: 10,
    padding: 20,
  },
  expenseCard: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 16,
    margin: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  expenseInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    margin: 16,
  },
  expenseInput: {
    borderBottomWidth: 1,
    borderBottomColor: "#CCC",
    width: 200,
    marginRight: 10,
    padding: 8,
  },
  addButton: {
    backgroundColor: "#FF7029",
    padding: 10,
    borderRadius: 5,
  },
  addButtonText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  savingItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 4,
  },
  removeText: {
    color: "red",
    marginLeft: 10,
  },
  restaurantCard: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 16,
    margin: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  restaurantName: {
    fontSize: 16,
    fontWeight: "bold",
  },
  restaurantBudget: {
    fontSize: 14,
    color: "#7D848D",
  },
  restaurantUrl: {
    fontSize: 14,
    color: "#1E90FF",
  },
  itineraryCard: {
    backgroundColor: "#FFF",
    borderRadius: 8,
    padding: 16,
    margin: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  itineraryActivity: {
    fontSize: 16,
    fontWeight: "bold",
  },
  itineraryDate: {
    fontSize: 14,
    color: "#7D848D",
  },
  itineraryDescription: {
    fontSize: 14,
    color: "#444",
  },
  editButton: {
    backgroundColor: "#FF7029",
    padding: 10,
    borderRadius: 28,
    marginVertical: 10,
    marginLeft: 20,
    width: 42,
    height: 42,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  editButtonText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  saveButton: {
    backgroundColor: "#4CAF50",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    flex: 1,
    marginHorizontal: 5,
  },
  saveButtonText: {
    color: "#FFF",
    fontWeight: "bold",
  },
  input: {
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 5,
    padding: 10,
    marginVertical: 5,
    width: "100%",
  },
  inputContainer: {
    width: "90%",
    paddingHorizontal: 20,
    marginVertical: 10,
    alignSelf: "center",
  },
  label: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 5,
  },
  inputTouchable: {
    backgroundColor: "#FFF",
    padding: 10,
    borderRadius: 5,
    marginVertical: 5,
    width: "90%",
    alignSelf: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "bold",
  },
  inputText: {
    fontSize: 16,
    color: "#333",
  },
  bannerButton: {
    width: "100%",
    height: 150,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 5,
  },
  bannerImage: {
    width: "100%",
    height: "100%",
    borderRadius: 5,
  },
  imageSlider: {
    marginTop: 10,
  },
  image: {
    width: 64,
    height: 64,
    borderRadius: 5,
    marginRight: 10,
  },
  deleteButton: {
    position: "absolute",
    top: 5,
    right: 5,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    borderRadius: 12,
    padding: 4,
  },
  backgroundImage: {
    flex: 1,
    resizeMode: "cover",
  },
  imageStyle: {
    opacity: 0.7,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
  },
  addRestaurantForm: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "#f2f2f2",
    borderRadius: 8,
  },
  addItineraryForm: {
    marginTop: 20,
    padding: 16,
    backgroundColor: "#f2f2f2",
    borderRadius: 8,
  },
});

export default styles;
